# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-07-19 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='date',
            field=models.DateField(default='2018-07-19'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='route.Route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(help_text='Route title or subject or purpose', max_length=50),
        ),
        migrations.RemoveField(
            model_name='route',
            name='created_on',
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set([('user', 'date')]),
        ),
    ]
